apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiftops-app-green
  namespace: production-green
  labels:
    app: shiftops-app
    env: green
    color: green
spec:
  replicas: 5
  selector:
    matchLabels:
      app: shiftops-app
      env: green
  template:
    metadata:
      labels:
        app: shiftops-app
        env: green
        color: green
    spec:
      containers:
      - name: server
        image: arnazz10/shiftops-app:v2.1.0-green
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
