apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiftops-app-blue
  namespace: production-blue
  labels:
    app: shiftops-app
    env: blue
    color: blue
spec:
  replicas: 5
  selector:
    matchLabels:
      app: shiftops-app
      env: blue
  template:
    metadata:
      labels:
        app: shiftops-app
        env: blue
        color: blue
    spec:
      containers:
      - name: server
        image: arnazz10/shiftops-app:v2.0.8-blue
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shiftops-service
  namespace: production-global
spec:
  type: LoadBalancer
  selector:
    app: shiftops-app
    color: blue # This selector is changed to 'green' during traffic switch
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
